#+TITLE: TODOs for Princeton Distiller

* Ad Hoc TODOs
** TODO [#C] Consider adding lxml type stubs
:PROPERTIES:
:CUSTOM_ID: add-lxml-type-stubs
:ASSIGNEES: Claude
:END:

- Motivation :: In [[file:~/repos/gh/pulibrary/periodical-distiller/src/schemas/article.py][article.py]], basedpyright complains that =_Element= is
not known.
- Suggested Action :: Add type hints for lxml using [[https://github.com/lxml/lxml-stubs/blob/master/lxml-stubs/etree.pyi][lxml-stubs]].
** DONE Create Pydantic schema for CEO3 Items
CLOSED: [2026-01-30]
:PROPERTIES:
:ASSIGNEES: Claude
:CUSTOM_ID: create-pydantic-schema-for-ceoitems
:COMMIT: 18d986d
:END:

- Motivation :: The CEOClient needs this schema to validate data it
  fetches; other components will use it to access record fields.

*** References
- [[https://docs.getsnworks.com/ceo2/front-end/json-api.html][CEO FrontEnd JSON API]]

** DONE Fix bug: API request fails with a 403 error                    :BUG:
CLOSED: [2026-01-30]
:PROPERTIES:
:ASSIGNEES: Claude
:CUSTOM_ID: API-request-fails
:COMMIT: 99e6967
:END:

#+begin_src bash
  pdm run python -m periodical_distiller.cli harvest-pip --date 2026-01-15
  INFO: Fetching articles for 2026-01-15
  INFO: HTTP Request: GET https://www.dailyprincetonian.com/api/content/v1/content?limit=100&offset=0&start_date=2026-01-15&end_date=2026-01-15 "HTTP/1.1 403 Forbidden"
  ERROR: Failed to create PIP: API error 403: https://www.dailyprincetonian.com/api/content/v1/content?limit=100&offset=0&start_date=2026-01-15&end_date=2026-01-15
#+end_src
** DONE Fix bug: media requests fail with 404                          :BUG:
CLOSED: [2026-01-31]
:PROPERTIES:
:ASSIGNEES: Claude
:CUSTOM_ID: media-request-fails
:END:
- Root cause :: Incorrect imgix CDN URL format. Was using
  ~{attachment_uuid}/{base_name}.{extension}~ but the correct format is
  ~pri/{attachment_uuid}.sized-1000x1000.{extension}~.
#+begin_src bash
  pdm run python -m periodical_distiller.cli harvest-pip --date 2026-01-29
  INFO: Fetching articles for 2026-01-29
  INFO: HTTP Request: GET https://www.dailyprincetonian.com/section/news.json?page=1&perPage=100 "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/f1b219da-32c6-4256-9536-4d94f3b39289/annie-rupertus-spia-plaza-spring-2.jpg "HTTP/1.1 404 Not Found"
  WARNING: Failed to download media for article 73628: HTTP 404
  INFO: HTTP Request: GET https://snworksceo.imgix.net/075988f6-5052-4285-8512-c49c4209bbfb/img-2413.jpg "HTTP/1.1 404 Not Found"
  WARNING: Failed to download media for article 73623: HTTP 404
  INFO: Created PIP 2026-01-29 with 2 articles at workspace/pips/2026-01-29
  INFO: Created PIP: 2026-01-29
  INFO:   Title: The Daily Princetonian - January 29, 2026
  INFO:   Articles: 2
  INFO:   Output: workspace/pips/2026-01-29
#+end_src
** DONE Fix bug: Flourish redirects and HEIC media downloads            :BUG:
CLOSED: [2026-01-31]
:PROPERTIES:
:ASSIGNEES: Claude
:CUSTOM_ID: media-request-fails-again
:END:
- Symptoms ::
  1. Flourish chart thumbnails failed with HTTP 302 (redirect not followed)
  2. HEIC media files failed with HTTP 404

- Root causes and fixes ::
  1. *Flourish 302*: httpx client wasn't configured to follow redirects.
     Fixed by adding ~follow_redirects=True~ to the httpx.Client constructor.
  2. *HEIC 404*: imgix stores HEIC files as PNG, not with original extension.
     Fixed by adding fallback URL logic that tries multiple extensions
     (jpg, png) when the primary URL returns 404.

- Changes ::
  - ~MediaDownloader._get_client()~: Added ~follow_redirects=True~
  - ~MediaDownloader._build_media_urls()~: New method returning list of
    fallback URLs for HEIC files (sized jpg, sized png, unsized jpg, unsized png)
  - ~MediaDownloader._download_dominant_media()~: Now tries fallback URLs
    when primary returns 404

*** Original bug report
1. Code isn't following 302 redirect.  For example,
   #+begin_example
       INFO: HTTP Request: GET https://public.flourish.studio/visualisation/26729538/thumbnail "HTTP/1.1 302 Found"
       WARNING: Failed to download Flourish chart 26729538 for article 73431: HTTP 302
   #+end_example

   https://public.flourish.studio/visualisation/26729538/thumbnail resolves to https://public.flourish.studio/published_thumbnails/visualisation/26729538/04d5600837812eaa.jpg

2. Not handling media with .heic extension.  For example,
   #+begin_example
       INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/1348d282-34ee-4cae-a78c-d4ae7c0f8e12.sized-1000x1000.heic "HTTP/1.1 404 Not Found"
       WARNING: Failed to download media for article 73405: HTTP 404
   #+end_example

   Adding ?fm=jpg extension still causes a 404:

   #+begin_example
     INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/1348d282-34ee-4cae-a78c-d4ae7c0f8e12.sized-1000x1000.heic?fm=jpg "HTTP/1.1 404 Not Found"
     WARNING: Failed to download media for article 73405: HTTP 404
   #+end_example
*** Example of run with warnings
#+begin_src bash
  pdm run python -m periodical_distiller.cli harvest-pip --start 2025-12-01 --end 2025-12-31
  INFO: Fetching articles from 2025-12-01 to 2025-12-31
  INFO: HTTP Request: GET https://www.dailyprincetonian.com/section/news.json?page=1&perPage=100 "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://www.dailyprincetonian.com/section/news.json?page=2&perPage=100 "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://www.dailyprincetonian.com/section/news.json?page=3&perPage=100 "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/78247f7f-86eb-43cc-bfe9-0ce9fd8c4fa7.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/a27b9250-8e67-4c42-a829-768a8a36154f.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/9335c9cc-5fb2-4105-b957-70760bd13819.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/049a5cf5-95a8-46d5-b71c-1071851c3b8c.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/20f26a01-f19d-49e0-9735-48d840bba8a7.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/6095c9a0-5e6d-4e85-8c1d-b1ab6e8f26d9.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/bb75da69-4e6c-49f2-a3b1-e8dc83140684.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/02239673-3c9d-41e2-a2d2-ecbd7e76dec6.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/2072a361-eea7-4f6f-8319-8d49241b704c.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/a51cf533-66ca-4bf6-855d-c2114d2aa7e3.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/31196c9c-4241-4cdc-8b75-fbc8bb880a47.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/e3afdc2e-0ebf-4efe-a38f-f0096f7302f5.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/73075927-109d-4382-beaa-dd49b66d5807.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/706885db-efcb-4db1-99a7-1d61d34967e2.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/a045b640-1749-4bb7-8177-39d1e1889cac.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/6962fb33-f162-4369-ad9d-1004ab0f5239.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://public.flourish.studio/visualisation/26729538/thumbnail "HTTP/1.1 302 Found"
  WARNING: Failed to download Flourish chart 26729538 for article 73431: HTTP 302
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/d80e84f1-86ec-4c93-8c41-7d79ffd5b421.sized-1000x1000.JPG "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/3f1ba838-7da8-4803-a446-f68dc287a6ae.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/c4b2958b-f7f3-414e-94de-6be7c7ff0ec2.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/03d15d3a-c5f9-4036-8f5b-a482d87d7d79.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/095c052a-5d8e-4408-9549-fef57f23f9cf.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/1a55e492-28fb-4cd4-b2a9-81bc32da6c10.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/1348d282-34ee-4cae-a78c-d4ae7c0f8e12.sized-1000x1000.heic "HTTP/1.1 404 Not Found"
  WARNING: Failed to download media for article 73405: HTTP 404
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/6ce86fa9-c9f6-4baa-9520-ad123640c783.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/2acde15b-8055-4852-a457-01c92d481f89.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/7a84b9ed-95ce-46bc-98da-40726f471bb1.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/fbac5f2e-fc66-44f2-b027-f8d6ad43e636.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/cb14b6e0-0727-481f-a6f3-d8c3338cd2d0.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/87a8c069-7228-487a-a020-d5d3d011aaf9.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/f13358c9-c675-4bde-8b9c-f59657c707e3.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/2a9fa40b-f4ff-463e-983f-7a604b6b75ca.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/0d374239-a19c-40d8-b6cc-f9fb0be36beb.sized-1000x1000.heic "HTTP/1.1 404 Not Found"
  WARNING: Failed to download media for article 73351: HTTP 404
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/dfaa43a0-d2c9-4557-8066-4f8a74d8ebd0.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/a85efd82-45f1-4819-82bd-02052d365bc6.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: HTTP Request: GET https://snworksceo.imgix.net/pri/5c392e4c-5e8f-4b93-b0f2-b513cc2f1005.sized-1000x1000.jpg "HTTP/1.1 200 OK"
  INFO: Created PIP 2025-12-01_to_2025-12-31 with 35 articles at workspace/pips/2025-12-01_to_2025-12-31
  INFO: Created PIP: 2025-12-01_to_2025-12-31
  INFO:   Title: The Daily Princetonian - December 01, 2025 to December 31, 2025
  INFO:   Articles: 35
  INFO:   Output: workspace/pips/2025-12-01_to_2025-12-31
#+end_src
